set_property SRC_FILE_INFO {cfile:/home/sirisli/soc_code_yqjing/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.srcs/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xdc rfile:../xilinx/xlnx_clk_gen/xlnx_clk_gen.srcs/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xdc id:1 order:EARLY scoped_inst:i_xlnx_clk_gen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sirisli/soc_code_yqjing/corev_apu/fpga/constraints/ariane.xdc rfile:../constraints/ariane.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.05
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets tck_IBUF_inst/O]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter tck 1.000
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_resp/i_src/data_src_q_reg*/C] -to [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_resp/i_dst/data_dst_q_reg*/D] 20.000
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_resp/i_src/req_src_q_reg/C] -to [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_resp/i_dst/req_dst_q_reg/D] 20.000
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_req/i_dst/ack_dst_q_reg/C] -to [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_req/i_src/ack_src_q_reg/D] 20.000
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold -from [get_pins {i_rstgen_main/i_rstgen_bypass/synch_regs_q_reg[3]/C}] 3
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clk]]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[version][0]} {i_dm_top/i_dm_csrs/dmstatus[version][1]} {i_dm_top/i_dm_csrs/dmstatus[version][2]} {i_dm_top/i_dm_csrs/dmstatus[version][3]}]]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_dm_top/i_dm_csrs/haltreq_o[0]}]]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[zero1][23]} {i_dm_top/i_dm_csrs/dmstatus[zero1][24]} {i_dm_top/i_dm_csrs/dmstatus[zero1][25]} {i_dm_top/i_dm_csrs/dmstatus[zero1][26]} {i_dm_top/i_dm_csrs/dmstatus[zero1][27]} {i_dm_top/i_dm_csrs/dmstatus[zero1][28]} {i_dm_top/i_dm_csrs/dmstatus[zero1][29]} {i_dm_top/i_dm_csrs/dmstatus[zero1][30]} {i_dm_top/i_dm_csrs/dmstatus[zero1][31]}]]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[zero0][20]} {i_dm_top/i_dm_csrs/dmstatus[zero0][21]}]]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {i_dm_top/i_dm_csrs/dmi_req_i[op][0]} {i_dm_top/i_dm_csrs/dmi_req_i[op][1]}]]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {i_dm_top/i_dm_csrs/dmi_req_i[data][0]} {i_dm_top/i_dm_csrs/dmi_req_i[data][1]} {i_dm_top/i_dm_csrs/dmi_req_i[data][2]} {i_dm_top/i_dm_csrs/dmi_req_i[data][3]} {i_dm_top/i_dm_csrs/dmi_req_i[data][4]} {i_dm_top/i_dm_csrs/dmi_req_i[data][5]} {i_dm_top/i_dm_csrs/dmi_req_i[data][6]} {i_dm_top/i_dm_csrs/dmi_req_i[data][7]} {i_dm_top/i_dm_csrs/dmi_req_i[data][8]} {i_dm_top/i_dm_csrs/dmi_req_i[data][9]} {i_dm_top/i_dm_csrs/dmi_req_i[data][10]} {i_dm_top/i_dm_csrs/dmi_req_i[data][11]} {i_dm_top/i_dm_csrs/dmi_req_i[data][12]} {i_dm_top/i_dm_csrs/dmi_req_i[data][13]} {i_dm_top/i_dm_csrs/dmi_req_i[data][14]} {i_dm_top/i_dm_csrs/dmi_req_i[data][15]} {i_dm_top/i_dm_csrs/dmi_req_i[data][16]} {i_dm_top/i_dm_csrs/dmi_req_i[data][17]} {i_dm_top/i_dm_csrs/dmi_req_i[data][18]} {i_dm_top/i_dm_csrs/dmi_req_i[data][19]} {i_dm_top/i_dm_csrs/dmi_req_i[data][20]} {i_dm_top/i_dm_csrs/dmi_req_i[data][21]} {i_dm_top/i_dm_csrs/dmi_req_i[data][22]} {i_dm_top/i_dm_csrs/dmi_req_i[data][23]} {i_dm_top/i_dm_csrs/dmi_req_i[data][24]} {i_dm_top/i_dm_csrs/dmi_req_i[data][25]} {i_dm_top/i_dm_csrs/dmi_req_i[data][26]} {i_dm_top/i_dm_csrs/dmi_req_i[data][27]} {i_dm_top/i_dm_csrs/dmi_req_i[data][28]} {i_dm_top/i_dm_csrs/dmi_req_i[data][29]} {i_dm_top/i_dm_csrs/dmi_req_i[data][30]} {i_dm_top/i_dm_csrs/dmi_req_i[data][31]}]]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 7 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {i_dm_top/i_dm_csrs/dmi_req_i[addr][0]} {i_dm_top/i_dm_csrs/dmi_req_i[addr][1]} {i_dm_top/i_dm_csrs/dmi_req_i[addr][2]} {i_dm_top/i_dm_csrs/dmi_req_i[addr][3]} {i_dm_top/i_dm_csrs/dmi_req_i[addr][4]} {i_dm_top/i_dm_csrs/dmi_req_i[addr][5]} {i_dm_top/i_dm_csrs/dmi_req_i[addr][6]}]]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {timer_cnt_tck[0]} {timer_cnt_tck[1]} {timer_cnt_tck[2]} {timer_cnt_tck[3]} {timer_cnt_tck[4]} {timer_cnt_tck[5]} {timer_cnt_tck[6]} {timer_cnt_tck[7]} {timer_cnt_tck[8]} {timer_cnt_tck[9]} {timer_cnt_tck[10]} {timer_cnt_tck[11]} {timer_cnt_tck[12]} {timer_cnt_tck[13]} {timer_cnt_tck[14]} {timer_cnt_tck[15]} {timer_cnt_tck[16]} {timer_cnt_tck[17]} {timer_cnt_tck[18]} {timer_cnt_tck[19]} {timer_cnt_tck[20]} {timer_cnt_tck[21]} {timer_cnt_tck[22]} {timer_cnt_tck[23]} {timer_cnt_tck[24]} {timer_cnt_tck[25]} {timer_cnt_tck[26]} {timer_cnt_tck[27]} {timer_cnt_tck[28]} {timer_cnt_tck[29]} {timer_cnt_tck[30]} {timer_cnt_tck[31]}]]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {timer_cnt[0]} {timer_cnt[1]} {timer_cnt[2]} {timer_cnt[3]} {timer_cnt[4]} {timer_cnt[5]} {timer_cnt[6]} {timer_cnt[7]} {timer_cnt[8]} {timer_cnt[9]} {timer_cnt[10]} {timer_cnt[11]} {timer_cnt[12]} {timer_cnt[13]} {timer_cnt[14]} {timer_cnt[15]} {timer_cnt[16]} {timer_cnt[17]} {timer_cnt[18]} {timer_cnt[19]} {timer_cnt[20]} {timer_cnt[21]} {timer_cnt[22]} {timer_cnt[23]} {timer_cnt[24]} {timer_cnt[25]} {timer_cnt[26]} {timer_cnt[27]} {timer_cnt[28]} {timer_cnt[29]} {timer_cnt[30]} {timer_cnt[31]}]]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {i_ariane/i_cva6/fetch_entry_if_id[address][0]} {i_ariane/i_cva6/fetch_entry_if_id[address][1]} {i_ariane/i_cva6/fetch_entry_if_id[address][2]} {i_ariane/i_cva6/fetch_entry_if_id[address][3]} {i_ariane/i_cva6/fetch_entry_if_id[address][4]} {i_ariane/i_cva6/fetch_entry_if_id[address][5]} {i_ariane/i_cva6/fetch_entry_if_id[address][6]} {i_ariane/i_cva6/fetch_entry_if_id[address][7]} {i_ariane/i_cva6/fetch_entry_if_id[address][8]} {i_ariane/i_cva6/fetch_entry_if_id[address][9]} {i_ariane/i_cva6/fetch_entry_if_id[address][10]} {i_ariane/i_cva6/fetch_entry_if_id[address][11]} {i_ariane/i_cva6/fetch_entry_if_id[address][12]} {i_ariane/i_cva6/fetch_entry_if_id[address][13]} {i_ariane/i_cva6/fetch_entry_if_id[address][14]} {i_ariane/i_cva6/fetch_entry_if_id[address][15]} {i_ariane/i_cva6/fetch_entry_if_id[address][16]} {i_ariane/i_cva6/fetch_entry_if_id[address][17]} {i_ariane/i_cva6/fetch_entry_if_id[address][18]} {i_ariane/i_cva6/fetch_entry_if_id[address][19]} {i_ariane/i_cva6/fetch_entry_if_id[address][20]} {i_ariane/i_cva6/fetch_entry_if_id[address][21]} {i_ariane/i_cva6/fetch_entry_if_id[address][22]} {i_ariane/i_cva6/fetch_entry_if_id[address][23]} {i_ariane/i_cva6/fetch_entry_if_id[address][24]} {i_ariane/i_cva6/fetch_entry_if_id[address][25]} {i_ariane/i_cva6/fetch_entry_if_id[address][26]} {i_ariane/i_cva6/fetch_entry_if_id[address][27]} {i_ariane/i_cva6/fetch_entry_if_id[address][28]} {i_ariane/i_cva6/fetch_entry_if_id[address][29]} {i_ariane/i_cva6/fetch_entry_if_id[address][30]} {i_ariane/i_cva6/fetch_entry_if_id[address][31]}]]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][0]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][1]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][2]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][3]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][4]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][5]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][6]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][7]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][8]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][9]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][10]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][11]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][12]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][13]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][14]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][15]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][16]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][17]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][18]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][19]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][20]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][21]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][22]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][23]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][24]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][25]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][26]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][27]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][28]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][29]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][30]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][predict_address][31]}]]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][cf][0]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][cf][1]} {i_ariane/i_cva6/fetch_entry_if_id[branch_predict][cf][2]}]]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][0]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][1]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][2]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][3]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][4]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][5]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][6]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][7]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][8]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][9]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][10]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][11]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][12]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][13]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][14]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][15]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][16]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][17]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][18]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][19]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][20]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][21]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][22]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][23]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][24]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][25]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][26]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][27]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][28]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][29]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][30]} {i_ariane/i_cva6/fetch_entry_if_id[ex][cause][31]}]]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {i_ariane/i_cva6/fetch_entry_if_id[instruction][0]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][1]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][2]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][3]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][4]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][5]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][6]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][7]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][8]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][9]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][10]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][11]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][12]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][13]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][14]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][15]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][16]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][17]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][18]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][19]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][20]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][21]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][22]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][23]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][24]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][25]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][26]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][27]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][28]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][29]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][30]} {i_ariane/i_cva6/fetch_entry_if_id[instruction][31]}]]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][0]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][1]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][2]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][3]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][4]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][5]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][6]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][7]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][8]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][9]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][10]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][11]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][12]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][13]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][14]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][15]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][16]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][17]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][18]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][19]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][20]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][21]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][22]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][23]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][24]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][25]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][26]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][27]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][28]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][29]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][30]} {i_ariane/i_cva6/fetch_entry_if_id[ex][tval][31]}]]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list clk]]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list debug_req_irq]]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list i_dm_top/i_dm_csrs/dmi_req_ready_o]]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list i_dm_top/i_dm_csrs/dmi_req_valid_i]]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[allhalted]}]]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[allhavereset]}]]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[allnonexistent]}]]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[allresumeack]}]]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[allrunning]}]]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[allunavail]}]]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[anyhalted]}]]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[anyhavereset]}]]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[anynonexistent]}]]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[anyresumeack]}]]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[anyrunning]}]]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[anyunavail]}]]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[authbusy]}]]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe32 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[authenticated]}]]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe33 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[devtreevalid]}]]
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe34 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[hasresethaltreq]}]]
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe35 [get_nets [list {i_dm_top/i_dm_csrs/dmstatus[impebreak]}]]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe36 [get_nets [list {i_ariane/i_cva6/fetch_entry_if_id[ex][valid]}]]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe37 [get_nets [list i_ariane/i_cva6/fetch_valid_if_id]]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe38 [get_nets [list i_dm_top/i_dm_mem/halted_d]]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe39 [get_nets [list i_dm_top/i_dm_mem/halted_q]]
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
